sudo: required
services:
  - docker

install:
  - cp config/database.yml.example config/database.yml
  - cp config/config.yml.example config/config.yml
  - cp db/schema.rb.example db/schema.rb
  - docker-compose up -d --build
  - docker-compose exec web bundle install
  - docker-compose exec web /bin/bash -lc "rake db:setup || rake db:migrate"

script:
  - docker-compose exec web rake test
